blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^bloggers/$', views.AuthorsList.as_view(), name='bloggers'),
    url(r'^blogger/(?P<pk>\d+)$', views.AuthorDetail.as_view(), name='author'),
    url(r'^blogs/$', views.BlogsList.as_view(), name='blogs'),
    url(r'^post/(?P<pk>\d+)$', views.BlogDetail.as_view(), name='blog'),
    url(r'^(?P<pk>\d+)/create$', views.CreateComment.as_view(), name='create_comment')
]

diyblog/urls.py
from django.contrib import admin
from django.urls import include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse

'''

comments
add post

'''


class Post(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField(max_length=3000, help_text='your description')
    author = models.ForeignKey('BlogAuthor', on_delete=models.SET_NULL, null=True)
    post_date = models.DateField(default=timezone.now)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog', args=[str(self.id)])

    class Meta:
        ordering = ['-post_date']


class BlogAuthor(models.Model):
    user = models.OneToOneField(User, on_delete=models.SET_NULL, null=True)
    bio = models.TextField(max_length=2000, help_text='your bio')

    def __str__(self):
        return self.user.username

    def get_absolute_url(self):
        return reverse('author', args=[str(self.id)])

    class Meta:
        ordering = ['user', 'bio']


class Comment(models.Model):
    description = models.TextField(1000, help_text='Enter comment about blog here.')
    post_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    post = models.ForeignKey('Post', on_delete=models.CASCADE)

    def __str__(self):
        len_default = 75
        if len(self.description) > len_default:
            out_title = self.description[:len_default] + '...'
        else:
            out_title = self.description
        return out_title

    class Meta:
        ordering = ['post_date']

blog/views.py
from django.shortcuts import render
from .models import Post, BlogAuthor, Comment
from django.views import generic
from django.shortcuts import get_object_or_404
# from django.shortcuts import redirect
from django.urls import reverse
# from django.contrib.auth.decorators import login_required
# from django.http import HttpResponseRedirect
# from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView


def index(request):
    num_author = BlogAuthor.objects.count()
    num_post = Post.objects.all().count()
    num_comment = Comment.objects.all().count()
    return render(request, 'index.html', context={'num_author': num_author, 'num_post': num_post,
                                                  'num_comment': num_comment})


class AuthorsList(generic.ListView):
    model = BlogAuthor
    paginate_by = 10


class BlogsList(generic.ListView):
    model = Post
    paginate_by = 10


class AuthorDetail(generic.ListView):
    model = Post
    paginate_by = 5
    template_name = 'blog/author_detail.html'

    def get_queryset(self):
        id = self.kwargs['pk']
        target_author = get_object_or_404(BlogAuthor, pk=id)
        return Post.objects.filter(author=target_author)

    def get_context_data(self, **kwargs):
        context = super(AuthorDetail, self).get_context_data(**kwargs)
        context['blogger'] = get_object_or_404(BlogAuthor, pk=self.kwargs['pk'])
        return context


class BlogDetail(generic.DetailView):
    model = Post


# @login_required(login_url='/accounts/login/')
# def create_comment(request, pk):
#     post_url = get_object_or_404(Post, pk=pk)
#
#     if request.method == 'POST':
#         form = CommentForm(request.POST)
#
#         if form.is_valid():
#             return redirect(reverse('blog', kwargs={'pk': pk}))
#
#     else:
#         form = CommentForm()
#
#     return render(request, 'blog/comment_form.html', {'form': form, 'post_url': post_url})


class CreateComment(LoginRequiredMixin, CreateView):
    model = Comment
    fields = ['description', ]

    def get_context_data(self, **kwargs):
        context = super(CreateComment, self).get_context_data(**kwargs)
        context['blog'] = get_object_or_404(Post, pk=self.kwargs['pk'])
        return context

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.post = get_object_or_404(Post, pk=self.kwargs['pk'])
        return super(CreateComment, self).form_valid(form)

    def get_success_url(self):
        return reverse('blog', kwargs={'pk': self.kwargs['pk']})

blog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}DIY Blog{% endblock %}</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
                integrity="sha256-pasqAKBDmFT4eHoN2ndd6lN370kFiGUFyTiUHWhU7k8="
                crossorigin="anonymous"></script>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
<!-- разобраться с css и сеттингами
     pagination
 -->
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-2">
                <ul class="sidebar-nav" style="list-style-type: none;">
                    <li><a href="{% url 'index' %}">Home</a></li>
                    <li><a href="{% url 'blogs' %}">All blogs</a></li>
                    <li><a href="{% url 'bloggers' %}">All bloggers</a></li>
                    {% if user.is_authenticated  %}
                        <li>User: {{ user.get_username }}</li>
                        <li><a href="{% url 'logout' %}?next={{ request.path }}">Logout</a></li>
                    {% else %}
                        <li><a href="{% url 'login' %}?next={{ request.path }}">Login</a></li>
                    {% endif %} 
                </ul>
            </div>
            <div class="col-sm-10">
                {% block content %}
                {% endblock %}

                {% if is_paginated %}
                  <div class="pagination">
                      <span class="page-links">
                          {% if page_obj.has_previous %}
                              <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                          {% endif %}
                          <span class="page-current">
                              Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                          </span>
                          {% if page_obj.has_next %}
                              <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                          {% endif %}
                      </span>
                  </div>
                {% endif %}
            </div>
        </div>
    </div>
</body>
</html>

blog/templates/blog/author_detail.html
{% extends 'base_generic.html' %}

{% block content %}

    <h1>Blogger: {{ blogger.user }}</h1>

    <h3>Bio</h3>
    <p>{{ blogger.bio }}</p>

    {% if post_list %}
        <h3>Blogs list</h3>

        <ul>
            {% for article in post_list %}

                <li><a href="{{ article.get_absolute_url }}">{{ article.title }}</a> ({{ article.post_date }})</li>

            {% endfor %}
        </ul>

    {% else %}
        <p>The Author has no posts</p>
    {% endif %}

{% endblock %}

blog/templates/blog/author_list.html
{% extends 'base_generic.html' %}

{% block content %}

    {% if author_list %}
        <ul>
            {% for author in author_list %}
                <li><a href="{{ author.get_absolute_url }}">{{ author.user.username }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>There are no bloggers in the site.</p>
    {% endif %}

{% endblock %}

blog/templates/blog/blogauthor_list.html
{% extends 'base_generic.html' %}

{% block content %}

    {% if blogauthor_list %}
        <ul>
            {% for author in blogauthor_list %}
                <li><a href="{{ author.get_absolute_url }}">{{ author.user.username }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>There are no bloggers in the site.</p>
    {% endif %}

{% endblock %}

blog/templates/blog/comment.html
{% extends 'base_generic.html' %}

{% block content %}
    <p>Post your comment for: <a href="{{ post_url.get_absolute_url }}">{{ post_url.title }}</a></p>
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form }}
        </table>
        <input type="submit" value="Submit">
    </form>
{% endblock %}

blog/templates/blog/comment_form.html
{% extends 'base_generic.html' %}

{% block content %}
    <p>Post your comment for: <a href="{{ post_url.get_absolute_url }}">{{ post_url.title }}</a></p>
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form }}
        </table>
        <input type="submit" value="Submit">
    </form>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'base_generic.html' %}

{% block content %}

    <h1>{{ post.title }}</h1>

    <p><strong>Post date </strong>{{ post.post_date }}</p>
    <p><strong>Author: </strong><a href="{{ post.author.get_absolute_url }}">{{ post.author }}</a></p>
    <p><strong>Description:</strong></p>
    <p>{{ post.description }}</p>

    <!-- Comments -->

    <p style="font-size: large;">Comments</p>
    
    {% for comment in post.comment_set.all %}
        <hr>
        {{ comment.author }} ({{ comment.post_date }}) - {{ comment }}
    {% endfor %}

    <hr>

    {% if user.is_authenticated %}
        <a href="{% url 'create_comment' post.pk %}">Add a new comment</a>
    {% else %}
        <p><a href="{% url 'login' %}?next={{ request.path }}">Login</a> to add a new comment</p>
    {% endif %}


{% endblock %}

blog/templates/blog/post_list.html
{% extends 'base_generic.html' %}

{% block content %}

    {% if post_list %}
        <ul>
            {% for blog in post_list %}
                <li><a href="{{ blog.get_absolute_url }}">{{ blog.title }}</a> ({{ blog.post_date }}) - <a href="{{ blog.author.get_absolute_url }}">{{ blog.author }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>There are no blogs in the site</p>
    {% endif %}

{% endblock %}

blog/templates/index.html
{% extends 'base_generic.html' %}

{% block content %}

    <h1 id="title">DIY Blog home</h1>
    <p>Welcome to <em>DjangoDIYBlog</em>, a very basic Django website.</p>
    <h2>Dynamic content</h2>
    <p>THe site has the following record counts:</p>

    <ul>
        <li><strong>Authors: </strong>{{ num_author }}</li>
        <li><strong>Posts: </strong>{{ num_post }}</li>
        <li><strong>Comments: </strong>{{ num_comment }}</li>
    </ul>

{% endblock %}